import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const options = {
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules],
  format: 'cjs',
  target: 'ES6',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
};

const copyWorker = () => {
  const workerSrc = path.join(process.cwd(), 'node_modules/pdfjs-dist/build/pdf.worker.min.js');
  const workerDest = path.join(process.cwd(), 'pdf.worker.min.js');

  if (fs.existsSync(workerSrc)) {
    fs.copyFileSync(workerSrc, workerDest);
    console.log('✓ PDF worker copied');
  }
};

copyWorker();

if (prod) {
  esbuild.buildSync(options);
} else {
  const ctx = await esbuild.context(options);
  await ctx.watch();
}
